-- Create a table for products
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric,
  image_url text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a table for users (admin)
create table Admin (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  
);



